### ISSUE TITLE
Need a valid "redirect_uri" to get my access token

### ISSUE THREAD

**Issue by hartmannn** [blackccpie/deezzy#2]
I'm following the procedure to get my access token, and the first dialog asks for three parameters including an URL, which isn't indicated in the instructions.

So could you please complete this URL for me ? (ie replace YOUR_REDIRECT_URI) ::
https://connect.deezer.com/oauth/auth.php?app_id=247082&redirect_uri=YOUR_REDIRECT_URI&perms=basic_access,email,manage_library

Thank you very much

**Comment by blackccpie** [comment]
Hi @hartmannn,

If I remember correctly, this _redirect uri_ is only used when using the deezer web api, to redirect user once authenticated. This is not our use case obviously because we are building a native player, so I think you can use whichever url you want to (I think I used the url of my github page).

Hope it helps

**Comment by hartmannn** [comment]
Thank you @blackccpie for your quick answer,

I tried https://connect.deezer.com/oauth/auth.php?app_id=247082&redirect_uri=https://github.com/blackccpie&perms=basic_access,email,manage_library as advised and got the following error message : You must specify a valid request_uri. 

On  [Deezer's documentation](https://developers.deezer.com/api/oauth) it is stated : " redirect_uri must be in the same domain as the domain you defined when you created the application" and that this parameter is mandatory.

Do you have any idea?

**Comment by blackccpie** [comment]
when you created your App, which domain did you use?
For exemple if you used *.deezer.com* then your _redirect uri_ should be something like *deezzy.deezer.com* (no matter if this is a dummy url).

**Comment by hartmannn** [comment]
I didn't create an app, I chose instead to keep the deezzy app id :"247082". So which domain did you use?

**Comment by blackccpie** [comment]
ok so I used the _.deezer.com_ domain, can you then try with _deezzy.deezer.com_ redirect uri?

**Comment by hartmannn** [comment]
Yes I did :
https://connect.deezer.com/oauth/auth.php?app_id=247082&redirect_uri=deezzy.deezer.com&perms=basic_access,email,manage_library

**Comment by blackccpie** [comment]
Hum, strange... I'm gonna make some tests and keep you updated. But I admit this part is not crystal clear in my documentation (as well as in Deezer's doc).

**Comment by blackccpie** [comment]
in fact forget about the domain thing, this url should work:
https://connect.deezer.com/oauth/auth.php?app_id=247082&redirect_uri=http://www.github.com/blackccpie&perms=basic_access,manage_library,email

you forgot the www. in your previous try

your key should be at the end of the new page url

**Comment by hartmannn** [comment]
It works! Thank you very much!

In fact I'm sure that I'm not the only one to ask myself this question, because it was already asked at the end of an article about your work published in a [french website](http://www.framboise314.fr/deezzy-un-lecteur-deezer-pour-le-raspberry-pi/#Compiler_Deezzy_sur_Raspberry_Pi).

**Comment by hartmannn** [comment]
For the next step I must fill this URL :: https://connect.deezer.com/oauth/access_token.php?app_id=YOU_APP_ID&secret=YOU_APP_SECRET&code=THE_CODE_FROM_ABOVE 

Deezer's documentation : "The app secret is available from the Application setting page and should not be shared with anyone or embedded in any code that you will distribute (you should use the client-side flow for these scenarios)"

I guess I will have to register your application under an other name. Doesn't it bother you? Can I use the GitHub page of Deezzy as link to "my" terms of use?

**Comment by blackccpie** [comment]
No problem for me if you create your application under another name.
I should remove the case where one use the same app id as I did from my doc, that's not a proper scenario.

**Comment by blackccpie** [comment]
@hartmannn : I'd be curious to know if you got the whole thing working, please let me know

**Comment by hartmannn** [comment]
OK, I will

**Comment by tyrower** [comment]
Thank you @blackccpie & @hartmannn. I got Deezzy working with my account thanks to your exchanges here. =oD Been waiting a long time to use Deezer on my Raspberry Pis!

**Comment by blackccpie** [comment]
@tyrower : great, glad to hear that!

**Comment by RTSaitama** [comment]
help me please, what exactly i should write in redirect -_- i tried on http://localhost:3000/, and its failed,tried on https://muz-project-gray.vercel.app/ and had the same( i tried with htttp, https, with no htttp\s ... same result ( ivalid redirect url and no deezer code :c
