### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by mjurinic** [blackccpie/deezzy#3]
Hey, would it be possible to run Deezzy in headless mode and have only audio?

**Comment by blackccpie** [comment]
@mjurinic : yes it is possible, you can start from the test app [here](https://github.com/blackccpie/deezzy/tree/master/tests) which is a good starting point, and does basically what you describe.

Hope it will help,

Albert

**Comment by blackccpie** [comment]
@mjurinic : can I close this issue now, did you manage to make the headless mode work?
