### ISSUE TITLE
No more native SDK

### ISSUE THREAD

**Issue by wibimaster** [blackccpie/deezzy#4]
Hi, 
all links to the native SDK and Deezer repo are dead, do you have a copy of these files ? Thanks !

**Comment by blackccpie** [comment]
Hi @wibimaster, can you send me private message to blackccpie@free.fr so that I can send you a download link?

thx

Albert

**Comment by wibimaster** [comment]
I've talk to Deezer tech' team and they give me a link, problem was my enterprise that lock Deezer repo IP :/ Sorry for that
